[package]
name = "payments-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1.6"
anyhow = "1.0.57"
clap = { version = "3.1.18", features = ["derive"] }
serde = { version = "1.0.137", features = ["derive"] }